# Name: Aishwarya Khairnar

# Task 3: Car Price Prediction

In [93]:
import numpy as np
import pandas as pd
from numpy import random
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

In [94]:
car=pd.read_csv(r"car data.csv")
car.head()

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Selling_type Transmission  Owner  
0       Dealer       Manual      0  
1       Dealer       Manual      0  
2       Dealer       Manual      0  
3       Dealer       Manual      0  
4       Dealer       Manual      0

In [95]:
car.shape

(301, 9)

In [96]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [97]:
car.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [98]:
num_cols = car._get_numeric_data().columns
num_cols

Index(['Year', 'Selling_Price', 'Present_Price', 'Driven_kms', 'Owner'], dtype='object')

In [99]:
car.Car_Name.nunique()

98

In [100]:
car = car.drop(columns = 'Car_Name')

In [101]:
car.head(2)

Year  Selling_Price  Present_Price  Driven_kms Fuel_Type Selling_type  \
0  2014           3.35           5.59       27000    Petrol       Dealer   
1  2013           4.75           9.54       43000    Diesel       Dealer   

  Transmission  Owner  
0       Manual      0  
1       Manual      0

In [102]:
car.Year.unique()

array([2014, 2013, 2017, 2011, 2018, 2015, 2016, 2009, 2010, 2012, 2003,
       2008, 2006, 2005, 2004, 2007], dtype=int64)

In [111]:
car.Fuel_Type.unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [112]:
car.Selling_type.unique()

array(['Dealer', 'Individual'], dtype=object)

In [113]:
car.Transmission.unique()

array(['Manual', 'Automatic'], dtype=object)

In [106]:
car.Owner.unique()

array([0, 1, 3], dtype=int64)

In [123]:
from sklearn.preprocessing import minmax_scale

car['Year'] = minmax_scale(car['Year'])
car['Driven_kms'] = minmax_scale(car['Driven_kms'])

In [124]:
car.head()

Year  Selling_Price  Present_Price  Driven_kms  Fuel_Type  \
0  0.733333           3.35           5.59    0.053053          0   
1  0.666667           4.75           9.54    0.085085          1   
2  0.933333           7.25           9.85    0.012813          0   
3  0.533333           2.85           4.15    0.009409          0   
4  0.733333           4.60           6.87    0.083984          1   

   Selling_type  Transmission  Owner  
0             0             0      0  
1             0             0      0  
2             0             0      0  
3             0             0      0  
4             0             0      0

In [125]:
cat_features = car[["Fuel_Type", "Selling_type","Transmission"]]

In [126]:
car.head(3)

Year  Selling_Price  Present_Price  Driven_kms  Fuel_Type  \
0  0.733333           3.35           5.59    0.053053          0   
1  0.666667           4.75           9.54    0.085085          1   
2  0.933333           7.25           9.85    0.012813          0   

   Selling_type  Transmission  Owner  
0             0             0      0  
1             0             0      0  
2             0             0      0

In [127]:
dic1 = {'Petrol':0, 'Diesel':1, 'CNG':2}
dic2 = {'Dealer':0, 'Individual':1}
dic3 = {'Manual':0, 'Automatic':1}

In [128]:
car.Fuel_Type.replace(dic1,inplace=True)

In [129]:
car.Selling_type.replace(dic2,inplace=True)

In [130]:
car.Transmission.replace(dic3,inplace=True)

In [131]:
car.head()

Year  Selling_Price  Present_Price  Driven_kms  Fuel_Type  \
0  0.733333           3.35           5.59    0.053053          0   
1  0.666667           4.75           9.54    0.085085          1   
2  0.933333           7.25           9.85    0.012813          0   
3  0.533333           2.85           4.15    0.009409          0   
4  0.733333           4.60           6.87    0.083984          1   

   Selling_type  Transmission  Owner  
0             0             0      0  
1             0             0      0  
2             0             0      0  
3             0             0      0  
4             0             0      0

In [132]:
X = car.drop(columns=['Selling_Price'])
y = car['Selling_Price']

In [135]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [136]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((240, 7), (61, 7), (240,), (61,))

In [139]:
y_train

74      4.90
239     2.00
64     33.00
294     3.75
286     5.65
       ...  
251     5.00
192     0.20
117     1.10
47      1.05
172     0.40
Name: Selling_Price, Length: 240, dtype: float64

# Linear Regression

In [141]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [142]:
lr.fit(X_train,y_train)

LinearRegression()

In [145]:
y_pred = lr.predict(X_test)
y_pred

array([ 7.14996517e+00, -4.20847179e-01,  4.29246727e+00,  8.65301481e+00,
        1.41554176e+01,  4.90718876e+00,  3.53618007e+00,  1.44495781e+00,
        5.38398624e+00,  4.66948309e+00,  2.25718756e+00,  1.62232757e+00,
        5.10110906e+00,  7.63623627e+00,  8.24976882e+00,  1.42084334e+01,
        7.39904547e+00,  4.27903409e+00, -4.55287689e-01,  2.38890541e+00,
        5.03389649e+00,  3.81039388e+00,  6.50022123e+00,  8.14392071e+00,
       -1.92677569e+00,  1.94126475e+00, -8.18018877e-01,  8.21249401e-01,
        3.92789475e-03,  7.20907187e+00,  3.07994855e+00,  7.05020642e+00,
        7.21312430e-01,  7.54555876e+00,  3.57180554e+00,  1.81724643e+00,
        5.60509044e+00,  6.59112767e+00, -2.72999497e+00,  8.75737029e+00,
        8.83968279e+00,  1.99044734e+01,  4.40367947e+00,  3.86453932e+00,
        6.26350522e+00,  9.51536892e+00,  1.23036614e-01,  1.68806431e+00,
        5.17954939e+00,  6.95909840e+00,  8.16121688e+00,  4.19690607e+00,
        4.92822982e+00,  

In [150]:
y_test

223     8.25
150     0.50
226     5.25
296     9.50
52     18.00
       ...  
137     0.65
227     2.55
26      4.15
106     1.35
92      3.51
Name: Selling_Price, Length: 61, dtype: float64

# Accuracy

In [151]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn.metrics import confusion_matrix,classification_report,r2_score
r2_score = r2_score(y_test,y_pred)*100
print("Linear regression model accuracy:",r2_score)


Linear regression model accuracy: 91.33788577646797
